name: signup_adventure
description: FlutLab-ready Signup Adventure
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  confetti: ^0.7.0

flutter:
  uses-material-design: true
